// <auto-generated />
using Basic_Raytracer.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Basic_Raytracer.Migrations
{
    [DbContext(typeof(RaytraceContext))]
    partial class RaytraceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("Basic_Raytracer.Tables.Scene", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SceneName")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Scenes");
                });

            modelBuilder.Entity("Basic_Raytracer.Tables.Shape", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ColorBlue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ColorGreen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ColorRed")
                        .HasColumnType("INTEGER");

                    b.Property<double>("OriginX")
                        .HasColumnType("REAL");

                    b.Property<double>("OriginY")
                        .HasColumnType("REAL");

                    b.Property<double>("OriginZ")
                        .HasColumnType("REAL");

                    b.Property<int>("SceneID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShapeName")
                        .HasColumnType("TEXT");

                    b.Property<int>("ShapeTypeID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("SceneID");

                    b.HasIndex("ShapeTypeID");

                    b.ToTable("Shapes");
                });

            modelBuilder.Entity("Basic_Raytracer.Tables.ShapeType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShapeTypeName")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("ShapeTypes");
                });

            modelBuilder.Entity("Basic_Raytracer.Tables.Shape", b =>
                {
                    b.HasOne("Basic_Raytracer.Tables.Scene", "Scene")
                        .WithMany()
                        .HasForeignKey("SceneID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Basic_Raytracer.Tables.ShapeType", "ShapeType")
                        .WithMany()
                        .HasForeignKey("ShapeTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scene");

                    b.Navigation("ShapeType");
                });
#pragma warning restore 612, 618
        }
    }
}
